# Generated by Django 4.2.4 on 2023-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_function_based', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='salary',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
