# Generated by Django 4.2.4 on 2023-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_function_based', '0002_remove_customer_salary_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dof',
            field=models.DateField(blank=True, null=True),
        ),
    ]
