# Generated by Django 4.2.4 on 2023-08-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_function_based', '0003_alter_customer_dof'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimg/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dof',
            field=models.DateField(null=True),
        ),
    ]
